/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as balancerSwapSol from "./BalancerSwap.sol";
export type { balancerSwapSol };
import type * as uniSwapSol from "./UniSwap.sol";
export type { uniSwapSol };
export type { OneInchSwap } from "./OneInchSwap";
export type { ZeroExSwap } from "./ZeroExSwap";
