/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IConversion__factory } from "./IConversion__factory";
export { IEzio__factory } from "./IEzio__factory";
