/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  SwapCollector,
  SwapCollectorInterface,
} from "../../contracts/SwapCollector";

const _abi = [
  {
    inputs: [],
    name: "feeTier",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060838061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806372f5d98a14602d575b600080fd5b6035610bb881565b60405162ffffff909116815260200160405180910390f3fea264697066735822122021b25df7ad756e91b475449a96b3d8270b1b60ad9ff945d5ebcf7b0dfa7f9e0764736f6c63430008080033";

type SwapCollectorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SwapCollectorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SwapCollector__factory extends ContractFactory {
  constructor(...args: SwapCollectorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SwapCollector> {
    return super.deploy(overrides || {}) as Promise<SwapCollector>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SwapCollector {
    return super.attach(address) as SwapCollector;
  }
  override connect(signer: Signer): SwapCollector__factory {
    return super.connect(signer) as SwapCollector__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SwapCollectorInterface {
    return new utils.Interface(_abi) as SwapCollectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SwapCollector {
    return new Contract(address, _abi, signerOrProvider) as SwapCollector;
  }
}
