/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as conversionSol from "./Conversion.sol";
export type { conversionSol };
import type * as e2LpSol from "./E2LP.sol";
export type { e2LpSol };
import type * as ezTokenSol from "./EzToken.sol";
export type { ezTokenSol };
import type * as ezTreasurySol from "./EzTreasury.sol";
export type { ezTreasurySol };
import type * as swapCollectorSol from "./SwapCollector.sol";
export type { swapCollectorSol };
import type * as usdeSol from "./USDE.sol";
export type { usdeSol };
